spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/verhyppo/example-argocd.git
    targetRevision: master
namespace: testing-app
deployment:
  nginx: |
    ingress:
      extraHosts:
        - name: dev-picasso.brno.kmglobalrd.com
          path: /peng