apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.namespace }}
  source:
    path: postgresql
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}