nginx:
  ingress:
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    enabled: true
    hostname: ''
    extraHosts:
      - name: dev-picasso.brno.kmglobalrd.com
        path: /ping